-- =====================================================================
--  Birtek — Seed verisi (OTOMATİK ÜRETİLDİ: pnpm db:seed-sql)
--  Kaynak: lib/data/seed.ts — elle düzenlemeyin.
-- =====================================================================

-- Markalar
insert into public.brands (name, slug, logo_url, catalog_pdf_url, sort_order) values ('Grundfos', 'grundfos', null, null, 1) on conflict (slug) do nothing;
insert into public.brands (name, slug, logo_url, catalog_pdf_url, sort_order) values ('Wilo', 'wilo', null, null, 2) on conflict (slug) do nothing;
insert into public.brands (name, slug, logo_url, catalog_pdf_url, sort_order) values ('Viega', 'viega', null, null, 3) on conflict (slug) do nothing;
insert into public.brands (name, slug, logo_url, catalog_pdf_url, sort_order) values ('Geberit', 'geberit', null, null, 4) on conflict (slug) do nothing;
insert into public.brands (name, slug, logo_url, catalog_pdf_url, sort_order) values ('Festo', 'festo', null, null, 5) on conflict (slug) do nothing;
insert into public.brands (name, slug, logo_url, catalog_pdf_url, sort_order) values ('Würth', 'wurth', null, null, 6) on conflict (slug) do nothing;
insert into public.brands (name, slug, logo_url, catalog_pdf_url, sort_order) values ('Danfoss', 'danfoss', null, null, 7) on conflict (slug) do nothing;
insert into public.brands (name, slug, logo_url, catalog_pdf_url, sort_order) values ('Honeywell', 'honeywell', null, null, 8) on conflict (slug) do nothing;

-- Kategoriler
insert into public.categories (name, slug, sort_order) values ('Vana & Armatür', 'vana-armatur', 1) on conflict (slug) do nothing;
insert into public.categories (name, slug, sort_order) values ('Boru & Fittings', 'boru-fittings', 2) on conflict (slug) do nothing;
insert into public.categories (name, slug, sort_order) values ('Pompa & Hidrofor', 'pompa-hidrofor', 3) on conflict (slug) do nothing;
insert into public.categories (name, slug, sort_order) values ('Isıtma & Tesisat', 'isitma-tesisat', 4) on conflict (slug) do nothing;
insert into public.categories (name, slug, sort_order) values ('Bağlantı Elemanları', 'baglanti-elemanlari', 5) on conflict (slug) do nothing;
insert into public.categories (name, slug, sort_order) values ('Ölçü & Kontrol', 'olcu-kontrol', 6) on conflict (slug) do nothing;

-- Alt kategoriler
insert into public.subcategories (name, slug, category_id, sort_order) values ('Küresel Vana', 'kuresel-vana', (select id from public.categories where slug = 'vana-armatur'), 1) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Kelebek Vana', 'kelebek-vana', (select id from public.categories where slug = 'vana-armatur'), 2) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Çek Valf', 'cek-valf', (select id from public.categories where slug = 'vana-armatur'), 3) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Pislik Tutucu', 'pislik-tutucu', (select id from public.categories where slug = 'vana-armatur'), 4) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Çelik Boru', 'celik-boru', (select id from public.categories where slug = 'boru-fittings'), 1) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Paslanmaz Fittings', 'paslanmaz-fittings', (select id from public.categories where slug = 'boru-fittings'), 2) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('PPRC Boru & Ek', 'pprc-boru', (select id from public.categories where slug = 'boru-fittings'), 3) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Dirsek & Te', 'dirsek-te', (select id from public.categories where slug = 'boru-fittings'), 4) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Sirkülasyon Pompası', 'sirkulasyon-pompasi', (select id from public.categories where slug = 'pompa-hidrofor'), 1) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Dalgıç Pompa', 'dalgic-pompa', (select id from public.categories where slug = 'pompa-hidrofor'), 2) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Hidrofor', 'hidrofor', (select id from public.categories where slug = 'pompa-hidrofor'), 3) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Kollektör', 'kollektor', (select id from public.categories where slug = 'isitma-tesisat'), 1) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Vana Grubu', 'vana-grubu', (select id from public.categories where slug = 'isitma-tesisat'), 2) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Genleşme Tankı', 'genlesme-tanki', (select id from public.categories where slug = 'isitma-tesisat'), 3) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Kelepçe', 'kelepce', (select id from public.categories where slug = 'baglanti-elemanlari'), 1) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Conta & Sızdırmazlık', 'conta-sizdirmazlik', (select id from public.categories where slug = 'baglanti-elemanlari'), 2) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Cıvata & Somun', 'civata-somun', (select id from public.categories where slug = 'baglanti-elemanlari'), 3) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Manometre', 'manometre', (select id from public.categories where slug = 'olcu-kontrol'), 1) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Termometre', 'termometre', (select id from public.categories where slug = 'olcu-kontrol'), 2) on conflict (category_id, slug) do nothing;
insert into public.subcategories (name, slug, category_id, sort_order) values ('Basınç Düşürücü', 'basinc-dusurucu', (select id from public.categories where slug = 'olcu-kontrol'), 3) on conflict (category_id, slug) do nothing;

-- Ürünler
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Pirinç Küresel Vana DN15 PN25', 'pirinc-kuresel-vana-dn15-pn25', 'VN-KV-15-25', (select id from public.brands where slug = 'wurth'), (select id from public.categories where slug = 'vana-armatur'), (select id from public.subcategories where slug = 'kuresel-vana' and category_id = (select id from public.categories where slug = 'vana-armatur')), 142.5, 'TRY', 'adet', 20, null, 'Tam geçişli pirinç küresel vana, 1/2" iç-iç dişli. PN25 basınç sınıfı, su ve hava hatları için uygun. Çelik kollu, kromajlı yüzey.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Pirinç Küresel Vana DN25 PN25', 'pirinc-kuresel-vana-dn25-pn25', 'VN-KV-25-25', (select id from public.brands where slug = 'wurth'), (select id from public.categories where slug = 'vana-armatur'), (select id from public.subcategories where slug = 'kuresel-vana' and category_id = (select id from public.categories where slug = 'vana-armatur')), 268, 'TRY', 'adet', 20, null, '1" tam geçişli pirinç küresel vana. Sıcak su ve kalorifer tesisatına uygun, PN25 basınç sınıfı.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Paslanmaz Küresel Vana DN50 3 Parça', 'paslanmaz-kuresel-vana-dn50-3-parca', 'VN-PKV-50-3P', (select id from public.brands where slug = 'festo'), (select id from public.categories where slug = 'vana-armatur'), (select id from public.subcategories where slug = 'kuresel-vana' and category_id = (select id from public.categories where slug = 'vana-armatur')), 1240, 'TRY', 'adet', 20, null, 'AISI 316 paslanmaz çelik 3 parçalı küresel vana, DN50. Sökülebilir gövde, endüstriyel proses hatları için.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Wafer Tip Kelebek Vana DN100', 'wafer-kelebek-vana-dn100', 'VN-KB-100-W', (select id from public.brands where slug = 'danfoss'), (select id from public.categories where slug = 'vana-armatur'), (select id from public.subcategories where slug = 'kelebek-vana' and category_id = (select id from public.categories where slug = 'vana-armatur')), 1980, 'TRY', 'adet', 20, null, 'Wafer tip kelebek vana DN100, EPDM sızdırmazlık, döküm gövde. Kollu manuel kumanda. Soğutma ve su hatları.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Wafer Tip Kelebek Vana DN150', 'wafer-kelebek-vana-dn150', 'VN-KB-150-W', (select id from public.brands where slug = 'danfoss'), (select id from public.categories where slug = 'vana-armatur'), (select id from public.subcategories where slug = 'kelebek-vana' and category_id = (select id from public.categories where slug = 'vana-armatur')), 3150, 'TRY', 'adet', 20, null, 'Wafer tip kelebek vana DN150, redüktörlü dişli kumanda. EPDM conta, GG25 döküm gövde.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Yaylı Çek Valf DN32', 'yayli-cek-valf-dn32', 'VN-CV-32-Y', (select id from public.brands where slug = 'danfoss'), (select id from public.categories where slug = 'vana-armatur'), (select id from public.subcategories where slug = 'cek-valf' and category_id = (select id from public.categories where slug = 'vana-armatur')), 410, 'TRY', 'adet', 20, null, 'Pirinç gövde yaylı çek valf DN32, dişli bağlantı. Geri akışı önler, yatay/dikey montaj.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Pislik Tutucu Y Tip DN40', 'pislik-tutucu-y-tip-dn40', 'VN-PT-40-Y', (select id from public.brands where slug = 'honeywell'), (select id from public.categories where slug = 'vana-armatur'), (select id from public.subcategories where slug = 'pislik-tutucu' and category_id = (select id from public.categories where slug = 'vana-armatur')), 520, 'TRY', 'adet', 20, null, 'Y tip pislik tutucu DN40, paslanmaz filtre eleği. Pompa ve sayaç koruması için hat üzeri montaj.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Dikişli Siyah Çelik Boru DN50', 'dikisli-siyah-celik-boru-dn50', 'BR-CB-50', (select id from public.brands where slug = 'wurth'), (select id from public.categories where slug = 'boru-fittings'), (select id from public.subcategories where slug = 'celik-boru' and category_id = (select id from public.categories where slug = 'boru-fittings')), 285, 'TRY', 'mt', 20, null, 'Dikişli siyah çelik boru 2", TS EN 10255 standart. Kalorifer ve basınçlı su hatları için, 6 m boy.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Dikişsiz Çelik Boru DN80 Sch40', 'dikissiz-celik-boru-dn80-sch40', 'BR-CB-80-S40', (select id from public.brands where slug = 'wurth'), (select id from public.categories where slug = 'boru-fittings'), (select id from public.subcategories where slug = 'celik-boru' and category_id = (select id from public.categories where slug = 'boru-fittings')), 640, 'TRY', 'mt', 20, null, 'Dikişsiz çelik boru DN80, Schedule 40. Yüksek basınç proses ve buhar hatları için.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Paslanmaz Dirsek 90° DN42', 'paslanmaz-dirsek-90-dn42', 'FT-PS-90-42', (select id from public.brands where slug = 'viega'), (select id from public.categories where slug = 'boru-fittings'), (select id from public.subcategories where slug = 'paslanmaz-fittings' and category_id = (select id from public.categories where slug = 'boru-fittings')), 86.5, 'TRY', 'adet', 20, null, 'AISI 316L paslanmaz pres dirsek 90°, Ø42 mm. Press-fit sistem, içme suyu uyumlu conta.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Paslanmaz Te DN28', 'paslanmaz-te-dn28', 'FT-PS-TE-28', (select id from public.brands where slug = 'viega'), (select id from public.categories where slug = 'boru-fittings'), (select id from public.subcategories where slug = 'paslanmaz-fittings' and category_id = (select id from public.categories where slug = 'boru-fittings')), 74, 'TRY', 'adet', 20, null, 'Paslanmaz press te Ø28 mm, eşit çıkışlı. Sanayi ve tesisat hatlarında hızlı montaj.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('PPRC Boru PN20 Ø32', 'pprc-boru-pn20-32', 'BR-PPRC-32-20', (select id from public.brands where slug = 'geberit'), (select id from public.categories where slug = 'boru-fittings'), (select id from public.subcategories where slug = 'pprc-boru' and category_id = (select id from public.categories where slug = 'boru-fittings')), 58, 'TRY', 'mt', 20, null, 'PPRC boru PN20, Ø32 mm. Sıcak-soğuk temiz su tesisatı, füzyon kaynaklı birleşim. 4 m boy.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('PPRC Dirsek 90° Ø25', 'pprc-dirsek-90-25', 'FT-PPRC-90-25', (select id from public.brands where slug = 'geberit'), (select id from public.categories where slug = 'boru-fittings'), (select id from public.subcategories where slug = 'dirsek-te' and category_id = (select id from public.categories where slug = 'boru-fittings')), 9.75, 'TRY', 'adet', 20, null, 'PPRC dirsek 90°, Ø25 mm. Temiz su tesisatı için füzyon kaynaklı ek parçası.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Dövme Çelik Te DN25', 'dovme-celik-te-dn25', 'FT-CE-TE-25', (select id from public.brands where slug = 'wurth'), (select id from public.categories where slug = 'boru-fittings'), (select id from public.subcategories where slug = 'dirsek-te' and category_id = (select id from public.categories where slug = 'boru-fittings')), 64.5, 'TRY', 'adet', 20, null, 'Dövme çelik dişli te 1", siyah. Basınçlı hatlarda dayanıklı bağlantı elemanı.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Frekans Kontrollü Sirkülasyon Pompası 25-60', 'sirkulasyon-pompasi-25-60', 'PMP-SR-2560', (select id from public.brands where slug = 'grundfos'), (select id from public.categories where slug = 'pompa-hidrofor'), (select id from public.subcategories where slug = 'sirkulasyon-pompasi' and category_id = (select id from public.categories where slug = 'pompa-hidrofor')), 7450, 'TRY', 'adet', 20, null, 'Islak rotorlu, frekans konvertörlü sirkülasyon pompası 25/6-180. A enerji sınıfı, kalorifer tesisatı için.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Dik Milli Çok Kademeli Pompa CR5-12', 'cok-kademeli-pompa-cr5-12', 'PMP-CR5-12', (select id from public.brands where slug = 'grundfos'), (select id from public.categories where slug = 'pompa-hidrofor'), (select id from public.subcategories where slug = 'sirkulasyon-pompasi' and category_id = (select id from public.categories where slug = 'pompa-hidrofor')), 18950, 'TRY', 'adet', 20, null, 'Dik milli, çok kademeli santrifüj pompa CR5-12. Paslanmaz hidrolik, basınçlandırma ve transfer uygulamaları.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Dalgıç Drenaj Pompası 0.75kW', 'dalgic-drenaj-pompasi-075kw', 'PMP-DLG-075', (select id from public.brands where slug = 'wilo'), (select id from public.categories where slug = 'pompa-hidrofor'), (select id from public.subcategories where slug = 'dalgic-pompa' and category_id = (select id from public.categories where slug = 'pompa-hidrofor')), 9850, 'TRY', 'adet', 20, null, 'Paslanmaz gövdeli dalgıç drenaj pompası 0.75 kW, flatörlü. Pis su ve drenaj çukurları için.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Paket Hidrofor 2 Pompalı 1.5kW', 'paket-hidrofor-2-pompali-15kw', 'PMP-HDR-2x15', (select id from public.brands where slug = 'wilo'), (select id from public.categories where slug = 'pompa-hidrofor'), (select id from public.subcategories where slug = 'hidrofor' and category_id = (select id from public.categories where slug = 'pompa-hidrofor')), 64200, 'TRY', 'takım', 20, null, 'İki pompalı paket hidrofor sistemi, 2x1.5 kW, kontrol panolu. Bina ve site temiz su basınçlandırma.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Pirinç Kollektör 4 Çıkışlı 1"', 'pirinc-kollektor-4-cikis-1', 'IS-KOL-4-1', (select id from public.brands where slug = 'viega'), (select id from public.categories where slug = 'isitma-tesisat'), (select id from public.subcategories where slug = 'kollektor' and category_id = (select id from public.categories where slug = 'isitma-tesisat')), 1320, 'TRY', 'adet', 20, null, 'Yerden ısıtma için pirinç kollektör, 4 çıkışlı, debimetreli. 1" ana giriş, ayar vanalı.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Termostatik Vana Grubu Köşe', 'termostatik-vana-grubu-kose', 'IS-TVG-K', (select id from public.brands where slug = 'danfoss'), (select id from public.categories where slug = 'isitma-tesisat'), (select id from public.subcategories where slug = 'vana-grubu' and category_id = (select id from public.categories where slug = 'isitma-tesisat')), 685, 'TRY', 'takım', 20, null, 'Panel radyatör için köşe termostatik vana grubu. Termostatik kafa + geri dönüş vanası dahil.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Kapalı Genleşme Tankı 24 lt', 'kapali-genlesme-tanki-24lt', 'IS-GT-24', (select id from public.brands where slug = 'wilo'), (select id from public.categories where slug = 'isitma-tesisat'), (select id from public.subcategories where slug = 'genlesme-tanki' and category_id = (select id from public.categories where slug = 'isitma-tesisat')), 1180, 'TRY', 'adet', 20, null, 'Membranlı kapalı genleşme tankı 24 litre, 3 bar ön basınç. Kapalı ısıtma devreleri için.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Çift Vidalı Boru Kelepçesi DN50', 'cift-vidali-boru-kelepcesi-dn50', 'BG-KLP-50', (select id from public.brands where slug = 'wurth'), (select id from public.categories where slug = 'baglanti-elemanlari'), (select id from public.subcategories where slug = 'kelepce' and category_id = (select id from public.categories where slug = 'baglanti-elemanlari')), 38.5, 'TRY', 'adet', 20, null, 'Kauçuk takviyeli çift vidalı boru kelepçesi 2". M8/M10 kombine somunlu, galvaniz kaplı.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Klingerit Conta DN50 PN16', 'klingerit-conta-dn50-pn16', 'BG-CNT-50-16', (select id from public.brands where slug = 'wurth'), (select id from public.categories where slug = 'baglanti-elemanlari'), (select id from public.subcategories where slug = 'conta-sizdirmazlik' and category_id = (select id from public.categories where slug = 'baglanti-elemanlari')), 22, 'TRY', 'adet', 20, null, 'Flanş contası klingerit DN50 PN16. Yağ, su ve buhar hatlarına uygun sızdırmazlık elemanı.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Paslanmaz Cıvata Somun Set M12x40', 'paslanmaz-civata-somun-m12x40', 'BG-CS-M12-40', (select id from public.brands where slug = 'wurth'), (select id from public.categories where slug = 'baglanti-elemanlari'), (select id from public.subcategories where slug = 'civata-somun' and category_id = (select id from public.categories where slug = 'baglanti-elemanlari')), 14.75, 'TRY', 'takım', 20, null, 'A2 paslanmaz cıvata + somun + pul seti M12x40. Flanş ve kelepçe bağlantıları için.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Gliserinli Manometre 0-16 bar Ø63', 'gliserinli-manometre-0-16-bar-63', 'OK-MNM-16-63', (select id from public.brands where slug = 'honeywell'), (select id from public.categories where slug = 'olcu-kontrol'), (select id from public.subcategories where slug = 'manometre' and category_id = (select id from public.categories where slug = 'olcu-kontrol')), 245, 'TRY', 'adet', 20, null, 'Gliserin dolgulu manometre 0-16 bar, Ø63 mm kadran, alttan bağlantı 1/4". Titreşimli hatlar için.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Daldırma Termometre 0-120°C', 'daldirma-termometre-0-120', 'OK-TRM-120', (select id from public.brands where slug = 'honeywell'), (select id from public.categories where slug = 'olcu-kontrol'), (select id from public.subcategories where slug = 'termometre' and category_id = (select id from public.categories where slug = 'olcu-kontrol')), 190, 'TRY', 'adet', 20, null, 'Daldırma tip kadranlı termometre 0-120°C, kovanlı. Kalorifer ve sıcak su hatları sıcaklık ölçümü.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Basınç Düşürücü Vana DN20', 'basinc-dusurucu-vana-dn20', 'OK-BDV-20', (select id from public.brands where slug = 'honeywell'), (select id from public.categories where slug = 'olcu-kontrol'), (select id from public.subcategories where slug = 'basinc-dusurucu' and category_id = (select id from public.categories where slug = 'olcu-kontrol')), 1450, 'TRY', 'adet', 20, null, 'Ayarlanabilir basınç düşürücü vana DN20, manometre bağlantı çıkışlı. Şebeke basıncını sabitler.', true) on conflict (slug) do nothing;
insert into public.products (name, slug, sku, brand_id, category_id, subcategory_id, list_price, currency, unit, vat_rate, image_url, description, is_active) values ('Diferansiyel Basınç Anahtarı', 'diferansiyel-basinc-anahtari', 'OK-DBA-01', (select id from public.brands where slug = 'danfoss'), (select id from public.categories where slug = 'olcu-kontrol'), (select id from public.subcategories where slug = 'basinc-dusurucu' and category_id = (select id from public.categories where slug = 'olcu-kontrol')), 2380, 'TRY', 'adet', 20, null, 'Ayarlanabilir diferansiyel basınç anahtarı, pompa ve filtre kontrolü için. IP54 koruma.', true) on conflict (slug) do nothing;

